---
apiVersion: v1
kind: Service
metadata:
    name: microservice-service
    labels:
        app: microservice
spec:
    selector:
        app: microservice
    ports:
        - name: microservice-port
          port: 8001
          targetPort: 8001
          protocol: TCP
    type: LoadBalancer
---