---
apiVersion: v1
kind: Service
metadata:
    name: monolith-service
    labels:
        app: monolith
spec:
    selector:
        app: monolith
    ports:
        - name: monolith-port
          port: 8000
          targetPort: 8000
          protocol: TCP
    type: LoadBalancer
---