---
apiVersion: v1
kind: Service
metadata:
    name: webapp-service
    labels:
        app: webapp
spec:
    selector:
        app: webapp
    ports:
        - name: webapp-port
          port: 80
          targetPort: 80
          protocol: TCP
    type: LoadBalancer
---