---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: webapp-mf3-deployment
    labels:
        app: webapp
spec:
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    selector:
        matchLabels:
            app: webapp
    template:
        metadata:
            labels:
                app: webapp
        spec: 
            containers:
                - name: webapp-mf3
                  image: zachhamilton/appmod-webapp-mf3
                  ports: 
                      - containerPort: 80
                        protocol: TCP
---