---
apiVersion: v1
kind: Service
metadata:
    name: connect-service
    labels:
        app: connect
spec: 
    selector:
        app: connect
    ports:
        - name: connect-port
          port: 8083
          targetPort: 8083
          protocol: TCP
    type: LoadBalancer