---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
    labels: 
        db: postgres
spec:
    replicas: 1
    strategy:
        rollingUpdate: 
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    selector:
        matchLabels:
            db: postgres
    template:
        metadata:
            labels:
                db: postgres
        spec:
            containers:
                - name: postgres
                  image: zachhamilton/appmod-postgres
                  env:
                      - name: POSTGRES_USER
                        value: "postgres"
                      - name: POSTGRES_PASSWORD
                        value: "postgres"
                      - name: POSTGRES_DB
                        value: "postgres"
                  ports:
                      - containerPort: 5432
                        protocol: TCP
---